name: QA Github CI
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install packages
        run: npm ci

      - name: Install browsers
        run: npm exec playwright install --with-deps

      - name: Create .env
        run: |
          echo "BASE_URL_API=${{ vars.BASE_URL_API }}" >> .env
          echo "BASE_URL_UI=${{ vars.BASE_URL_UI }}" >> .env

      - name: Run tests
        run: npx playwright test

      - name: Add allure report
        run: npx allure-commandline generate ./allure-results -o ./allure-report --clean
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: false

      - name: Generate report URL
        run: |
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/index.html"
          echo "REPORT_URL=${REPORT_URL}" >> $GITHUB_ENV

      - name: Create telegram config
        run: |
          sed -e "s|\"reportLink\":.*|\"reportLink\": \"${{ env.REPORT_URL }}\",|" \
          -e "s|%%TELEGRAM_BOT_TOKEN%%|${{ secrets.TELEGRAM_BOT_TOKEN }}|" \
          -e "s|%%TELEGRAM_CHAT_ID%%|${{ secrets.TELEGRAM_CHAT_ID }}|" \
          notifications/telegram.template.json > notifications/telegram.json

      - name: Send notification in telegram
        run: java "-DconfigFile=notifications/telegram.json" -jar notifications/allure-notifications-4.11.0.jar
